apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  namespace: production
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      application: webpage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: webpage-pod
      labels:
        application: webpage
    spec:
      containers:
      - name: webpage-container
        image: 236536187964.dkr.ecr.ap-south-1.amazonaws.com/webapplication-argocd:29
        imagePullPolicy: Always
        ports:
        - containerPort: 8080